[package]
name = "ferrisdex"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dirs = "6"
http-cache-reqwest = { version = "1.0.0-alpha.5", features = ["manager-cacache"] }
image = "0.25"
reqwest = { version = "0.13.2", features = ["json"] }
reqwest-middleware = "0.5.1"
rustemon = "4.5.0"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt", "time"] }
toml = "1.1.0"
viuer = "0.11.0"
